//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDetail
    {
        public int dID { get; set; }
        public int mID { get; set; }
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string MemberBirth { get; set; }
        public string MemberBirthTime { get; set; }
        public string MemberBirthPlace { get; set; }
        public string MemberAstro { get; set; }
        public string MemberAstronut { get; set; }
    
        public virtual MemberForm MemberForm { get; set; }
    }
}
